# Generated by Django 4.0.5 on 2022-06-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='S_Category',
            new_name='Category',
        ),
    ]
