# Generated by Django 4.0.5 on 2022-06-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
