# Generated by Django 4.0.5 on 2022-06-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_create_date_review_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
